---
- connection: local
  hosts: localhost
  sudo: true
  remote_user: douglas
  tasks:
    - name: install software | apt
      apt:
        pkg: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - openjdk-9-jdk

    - name: reader | cron
      sudo_user: www-data
      cron:
        name: "Reader updater"
        special_time: reboot
        job: "cd /etc/SARAH/www/apps/Reader/updater/ &&  bash run.sh"
